// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2LJOVNk_mh36OWa66TTKQ5yxtJdErvOo',
    appId: '1:816305286247:web:58fa8dd36f350b19f538c2',
    messagingSenderId: '816305286247',
    projectId: 'returnly-13bfe',
    authDomain: 'returnly-13bfe.firebaseapp.com',
    storageBucket: 'returnly-13bfe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEVXxY-RmcYnAtamGsg3sR_mT7NoGIsKU',
    appId: '1:816305286247:android:210c57a21fc467d0f538c2',
    messagingSenderId: '816305286247',
    projectId: 'returnly-13bfe',
    storageBucket: 'returnly-13bfe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR1XNuG6lR5k2zgrDR2pgz55aoGwntBE8',
    appId: '1:816305286247:ios:3666de637a1aa845f538c2',
    messagingSenderId: '816305286247',
    projectId: 'returnly-13bfe',
    storageBucket: 'returnly-13bfe.firebasestorage.app',
    iosBundleId: 'com.example.returnly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR1XNuG6lR5k2zgrDR2pgz55aoGwntBE8',
    appId: '1:816305286247:ios:3666de637a1aa845f538c2',
    messagingSenderId: '816305286247',
    projectId: 'returnly-13bfe',
    storageBucket: 'returnly-13bfe.firebasestorage.app',
    iosBundleId: 'com.example.returnly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2LJOVNk_mh36OWa66TTKQ5yxtJdErvOo',
    appId: '1:816305286247:web:cdf07bb8c278ed4df538c2',
    messagingSenderId: '816305286247',
    projectId: 'returnly-13bfe',
    authDomain: 'returnly-13bfe.firebaseapp.com',
    storageBucket: 'returnly-13bfe.firebasestorage.app',
  );
}
